//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorized {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authorized.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access control entry subject identifier must be specified.
        /// </summary>
        internal static string ACE_SUBJECT_IDENTIFIER_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("ACE_SUBJECT_IDENTIFIER_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access control entry subject must be specified..
        /// </summary>
        internal static string ACE_SUBJECT_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("ACE_SUBJECT_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access control entry subject type must be specified.
        /// </summary>
        internal static string ACE_SUBJECT_TYPE_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("ACE_SUBJECT_TYPE_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object identifier must be specified.
        /// </summary>
        internal static string OBJECT_IDENTIFIER_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("OBJECT_IDENTIFIER_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type must be specified.
        /// </summary>
        internal static string OBJECT_TYPE_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("OBJECT_TYPE_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject identifier must be specified.
        /// </summary>
        internal static string SUBJECT_IDENTIFIER_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("SUBJECT_IDENTIFIER_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject type must be specified.
        /// </summary>
        internal static string SUBJECT_TYPE_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("SUBJECT_TYPE_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        internal static string VALUE_CANNOT_BE_NULL_OR_WHITESPACE {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_BE_NULL_OR_WHITESPACE", resourceCulture);
            }
        }
    }
}
