<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <Title>Pug.Authorized.Data.Common</Title>
        <Company>Pug Computing</Company>
        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/NDWX/Authorized.git</RepositoryUrl>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <PackageVersion>1.0.0</PackageVersion>
        <PackageLicenseExpression>Apache-2.0+</PackageLicenseExpression>
        <License>Apache2.0</License>
        <PackageTags>Pug.Authorized Authorization Framework Common DataAccess Library</PackageTags>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageReleaseNotes>Upgraded Pug.Application.Data.Common from v1.0.3 to v1.1.0.</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Pug.Application.Data.Common" Version="1.1.0" />
        <PackageReference Include="Pug.Application.Security.Models" Version="3.1.0" />
        <PackageReference Include="SonarAnalyzer.CSharp" Version="9.19.0.84025">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Pug.Authorized.Models\Pug.Authorized.Models.csproj" />
    </ItemGroup>
</Project>
