name: master - build and NuGet publish

on:
  push:
    tags:
      - release-*

env:
  BuildConfiguration: release
  ModelsProject: src/Pug.Authorized.Models/Pug.Authorized.Models.csproj
  CommonProject: src/Pug.Authorized.Common/Pug.Authorized.Common.csproj
  MainProject: src/Pug.Authorized/Pug.Authorized.csproj
  DataCommonProject: src/Pug.Authorized.Data.Common/Pug.Authorized.Data.Common.csproj
  SqlLiteDataProject: src/Pug.Authorized.Data.SqlLite/Pug.Authorized.Data.SqlLite.csproj
  DependencyInjectionProject: src/Pug.Authorized.DependencyInjection/Pug.Authorized.DependencyInjection.csproj
  RestProject: src/Pug.Authorized.WebApi/Pug.Authorized.WebApi.csproj
  PackagesBaseFolder: packages

jobs:
  build:
    name: Build and publish NuGet packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis


      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/Authorized/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore NuGet packages
        run: dotnet restore ${{env.Solution}}

      - name: Create packages base folder
        run: mkdir packages

      - name: Pack Models project
        run: dotnet pack --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.ModelsProject}}

      - name: Publish Models NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg

      - name: Pack Common project
        run: dotnet pack --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.CommonProject}}

      - name: Publish Common NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg

      - name: Pack DataCommonProject project
        run: dotnet pack --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.DataCommonProject}}

      - name: Publish DataCommon NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg

      - name: Pack Sqlite project
        run: dotnet pack --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.SqlLiteDataProject}}

      - name: Publish Sqlite  NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg

      - name: Pack Main project
        run: dotnet pack --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.MainProject}}

      - name: Publish Main NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg

      - name: Pack DependencyInjection project
        run: dotnet pack --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.DependencyInjectionProject}}

      - name: Publish DependencyInjection NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg

      - name: Pack Rest project
        run: dotnet pack --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.RestProject}}

      - name: Publish Rest NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg